[package]
name = "plain-sync"
version = "0.1.0"
authors = ["Stas Rudakou <stas@garage22.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "~0.10"